name: Build Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew remapJar --no-daemon
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: axe-warning
          path: build/libs/axe-warning-*.jar
